/**
 * Complete public-event contract. Each runtime component/event pair has one
 * entry so duplicate generic names (for example ren-open) remain traceable to
 * their source and may intentionally expose different flags.
 */
export const PUBLIC_EVENTS = [
  { component: 'ren-accordion', event: 'ren-accordion-change', bubbles: true, composed: false, cancelable: false, detail: ['item', 'isOpen', 'index'], source: 'components/composites/ren-accordion/ren-accordion.js' },
  { component: 'ren-calendar', event: 'ren-date-select', bubbles: true, composed: true, cancelable: false, detail: ['date', 'range', 'dates'], source: 'components/composites/ren-calendar/ren-calendar.js' },
  { component: 'ren-carousel', event: 'ren-slide-change', bubbles: true, composed: true, cancelable: false, detail: ['index', 'total', 'id'], source: 'components/composites/ren-carousel/ren-carousel.js' },
  { component: 'ren-color-picker', event: 'ren-input', bubbles: true, composed: true, cancelable: false, detail: ['hex', 'rgb', 'hsl', 'alpha'], source: 'components/composites/ren-color-picker/ren-color-picker.js' },
  { component: 'ren-color-picker', event: 'ren-change', bubbles: true, composed: true, cancelable: false, detail: ['hex', 'rgb', 'hsl', 'alpha'], source: 'components/composites/ren-color-picker/ren-color-picker.js' },
  { component: 'ren-combobox', event: 'ren-search', bubbles: true, composed: false, cancelable: false, detail: ['query'], source: 'components/composites/ren-combobox/ren-combobox.js' },
  { component: 'ren-combobox', event: 'ren-change', bubbles: true, composed: false, cancelable: false, detail: ['value', 'item'], source: 'components/composites/ren-combobox/ren-combobox.js' },
  { component: 'ren-combobox', event: 'ren-open', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-combobox/ren-combobox.js' },
  { component: 'ren-combobox', event: 'ren-close', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-combobox/ren-combobox.js' },
  { component: 'ren-context-menu', event: 'ren-context-menu-open', bubbles: true, composed: true, cancelable: false, detail: ['x', 'y', 'target'], source: 'components/composites/ren-context-menu/ren-context-menu.js' },
  { component: 'ren-date-picker', event: 'ren-date-picker-open', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-date-picker/ren-date-picker.js' },
  { component: 'ren-date-picker', event: 'ren-date-picker-close', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-date-picker/ren-date-picker.js' },
  { component: 'ren-date-picker', event: 'ren-change', bubbles: true, composed: true, cancelable: false, detail: ['value', 'formattedValue'], source: 'components/composites/ren-date-picker/ren-date-picker.js' },
  { component: 'ren-date-range-picker', event: 'ren-date-range-open', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-date-range-picker/ren-date-range-picker.js' },
  { component: 'ren-date-range-picker', event: 'ren-date-range-close', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-date-range-picker/ren-date-range-picker.js' },
  { component: 'ren-date-range-picker', event: 'ren-change', bubbles: true, composed: true, cancelable: false, detail: ['value', 'formattedValue', 'preset', 'days'], source: 'components/composites/ren-date-range-picker/ren-date-range-picker.js' },
  { component: 'ren-dialog', event: 'ren-open', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-dialog/ren-dialog.js' },
  { component: 'ren-dialog', event: 'ren-close', bubbles: true, composed: true, cancelable: false, detail: ['returnValue'], source: 'components/composites/ren-dialog/ren-dialog.js' },
  { component: 'ren-dropzone', event: 'ren-files-added', bubbles: true, composed: false, cancelable: false, detail: ['files'], source: 'components/composites/ren-dropzone/ren-dropzone.js' },
  { component: 'ren-hover-card', event: 'ren-hover-card-open', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-hover-card/ren-hover-card.js' },
  { component: 'ren-hover-card', event: 'ren-hover-card-close', bubbles: true, composed: true, cancelable: false, detail: [], source: 'components/composites/ren-hover-card/ren-hover-card.js' },
  { component: 'ren-menu', event: 'ren-menu-select', bubbles: true, composed: false, cancelable: false, detail: ['item', 'value'], source: 'components/composites/ren-menu/ren-menu.js' },
  { component: 'ren-menu', event: 'ren-menu-open', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-menu/ren-menu.js' },
  { component: 'ren-menu', event: 'ren-menu-close', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-menu/ren-menu.js' },
  { component: 'ren-number-field', event: 'ren-change', bubbles: true, composed: true, cancelable: false, detail: ['value', 'oldValue'], source: 'components/composites/ren-number-field/ren-number-field.js' },
  { component: 'ren-otp', event: 'ren-change', bubbles: true, composed: true, cancelable: false, detail: ['value'], source: 'components/composites/ren-otp/ren-otp.js' },
  { component: 'ren-otp', event: 'ren-complete', bubbles: true, composed: true, cancelable: false, detail: ['value'], source: 'components/composites/ren-otp/ren-otp.js' },
  { component: 'ren-popover', event: 'ren-open', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-popover/ren-popover.js' },
  { component: 'ren-popover', event: 'ren-close', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-popover/ren-popover.js' },
  { component: 'ren-select', event: 'ren-select-open', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-select/ren-select.js' },
  { component: 'ren-select', event: 'ren-select-close', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-select/ren-select.js' },
  { component: 'ren-select', event: 'ren-select-change', bubbles: true, composed: false, cancelable: false, detail: ['value', 'label', 'item'], source: 'components/composites/ren-select/ren-select.js' },
  { component: 'ren-sheet', event: 'ren-open', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-sheet/ren-sheet.js' },
  { component: 'ren-sheet', event: 'ren-close', bubbles: true, composed: true, cancelable: false, detail: ['returnValue'], source: 'components/composites/ren-sheet/ren-sheet.js' },
  { component: 'ren-slider', event: 'ren-slider-input', bubbles: true, composed: true, cancelable: false, detail: ['value'], source: 'components/composites/ren-slider/ren-slider.js' },
  { component: 'ren-slider', event: 'ren-slider-change', bubbles: true, composed: true, cancelable: false, detail: ['value'], source: 'components/composites/ren-slider/ren-slider.js' },
  { component: 'ren-tabs', event: 'ren-tab-change', bubbles: true, composed: true, cancelable: false, detail: ['tab', 'panel', 'index', 'id'], source: 'components/composites/ren-tabs/ren-tabs.js' },
  { component: 'ren-toggle-group', event: 'ren-toggle-change', bubbles: true, composed: true, cancelable: false, detail: ['value', 'items'], source: 'components/composites/ren-toggle-group/ren-toggle-group.js' },
  { component: 'ren-tooltip', event: 'ren-open', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-tooltip/ren-tooltip.js' },
  { component: 'ren-tooltip', event: 'ren-close', bubbles: true, composed: false, cancelable: false, detail: [], source: 'components/composites/ren-tooltip/ren-tooltip.js' },
  { component: 'ren-command', event: 'ren-command-select', bubbles: true, composed: true, cancelable: false, detail: ['item', 'value', 'action'], source: 'components/patterns/ren-command/ren-command.js' },
  { component: 'ren-form', event: 'ren-submit-error', bubbles: true, composed: true, cancelable: false, detail: ['error'], source: 'components/patterns/ren-form/ren-form.js' },
  { component: 'ren-form', event: 'ren-invalid', bubbles: true, composed: true, cancelable: false, detail: ['errors'], source: 'components/patterns/ren-form/ren-form.js' },
  { component: 'ren-form', event: 'ren-submit', bubbles: true, composed: true, cancelable: true, detail: ['values', 'form', 'waitUntil'], source: 'components/patterns/ren-form/ren-form.js' },
  { component: 'ren-form', event: 'ren-field-validated', bubbles: true, composed: true, cancelable: false, detail: ['name', 'valid', 'error'], source: 'components/patterns/ren-form/ren-form.js' },
  { component: 'ren-form', event: 'ren-step-change', bubbles: true, composed: true, cancelable: false, detail: ['step', 'totalSteps'], source: 'components/patterns/ren-form/ren-form.js' },
  { component: 'ren-menubar', event: 'ren-menubar-select', bubbles: true, composed: true, cancelable: false, detail: ['item', 'value', 'checked'], source: 'components/patterns/ren-menubar/ren-menubar.js' },
  { component: 'ren-sidebar', event: 'ren-sidebar-toggle', bubbles: true, composed: true, cancelable: false, detail: ['collapsed'], source: 'components/patterns/ren-sidebar/ren-sidebar.js' },
];
